server:
  port: 8080
  
mlrServicePassword: ${mlrServicePassword}

zuul:
  routes:
    legacyCru:
      path: /monitoringLocations/get/**
      stripPrefix: false

ddot:
  ribbon:
    listOfServers: ${ddotServers}

legacyTransformer:
  ribbon:
    listOfServers: ${legacyTransformerServers}

legacyValidator:
  ribbon:
    listOfServers: ${legacyValidatorServers}

legacyCru:
  ribbon:
    listOfServers: ${legacyCruServers}

fileExport:
  ribbon:
    listOfServers: ${fileExportServers}

notification:
  ribbon:
    listOfServers: ${notificationServers}

eureka:
  client:
    enabled: false

feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: ${ribbonMaxAutoRetries}
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: ${ribbonConnectTimeout}
  ReadTimeout: ${ribbonReadTimeout}
  OkToRetryOnAllOperations: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${hystrixThreadTimeout}

logging:
  level:
    org:
      springframework: ${springFrameworkLogLevel}
