server:
  port: ${serverPort:8443}
  use-forward-headers: true
  session:
    timeout: ${sessionTimeout:43200}
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
    enabled-protocols: TLSv1.2

additionalNotificationRecipients: ${mlrgateway_additionalNotificationRecipients:}


zuul:
  retryable: true
  ribbonIsolationStrategy: SEMAPHORE
  routes:
    legacyCruBase:
      path: /monitoringLocations**
      serviceId: legacyCru
      stripPrefix: false
    legacyCruPlus:
      path: /monitoringLocations/**
      serviceId: legacyCru
      stripPrefix: false

ddot:
  ribbon:
    listOfServers: ${mlrgateway_ddotServers}
    IsSecure: ${mlrgateway_ddotIsSecure:true}

legacyTransformer:
  ribbon:
    listOfServers: ${mlrgateway_legacyTransformerServers}
    IsSecure: ${mlrgateway_legacyTransformerIsSecure:true}

legacyValidator:
  ribbon:
    listOfServers: ${mlrgateway_legacyValidatorServers}
    IsSecure: ${mlrgateway_legacyValidatorIsSecure:true}

legacyCru:
  ribbon:
    listOfServers: ${mlrgateway_legacyCruServers}
    IsSecure: ${mlrgateway_legacyCruIsSecure:true}

fileExport:
  ribbon:
    listOfServers: ${mlrgateway_fileExportServers}
    IsSecure: ${mlrgateway_fileExportIsSecure:true}

notification:
  ribbon:
    listOfServers: ${mlrgateway_notificationServers}
    IsSecure: ${mlrgateway_notificationIsSecure:true}

eureka:
  client:
    enabled: false

feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: ${mlrgateway_ribbonMaxAutoRetries}
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: ${mlrgateway_ribbonConnectTimeout}
  ReadTimeout: ${mlrgateway_ribbonReadTimeout}
  OkToRetryOnAllOperations: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: ${mlrgateway_hystrixThreadTimeout}

logging:
  level:
    org:
      springframework: ${mlrgateway_springFrameworkLogLevel:INFO}

security:
  require-ssl: true
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ${oauthClientId}
      clientSecret: ${oauthClientSecret}
      accessTokenUri: ${oauthClientAccessTokenUri}
      userAuthorizationUri: ${oauthClientAuthorizationUri}
    resource:
      id: ${oauthResourceId}
      jwt:
        keyUri: ${oauthResourceTokenKeyUri}
  maintenanceRoles: ${maintenanceRoles:}
