server:
  port: 8080

zuul:
  routes:
    legacyCru:
      path: /monitoringLocations/**
      stripPrefix: false
    ddot:
      path: /ddots/**
      stripPrefix: false

legacyCru:
  ribbon:
    listOfServers: ${legacyCruServers}
    eureka:
      enabled: false

ddot:
  ribbon:
    listOfServers: ${ddotServers}
    eureka:
      enabled: false

eureka:
  client:
    enabled: false

feign:
  hystix:
    enabled: true