server:
  port: 8080

mlrServicePassword: ${mlrgateway_mlrServicePassword}
temporaryNotificationEmail: ${mlrgateway_temporaryNotificationEmail}
dbInitializerEnabled: true

zuul:
  retryable: true
  ribbonIsolationStrategy: SEMAPHORE
  routes:
    legacyCru:
      path: /monitoringLocations/**
      stripPrefix: false

ddot:
  ribbon:
    listOfServers: ${mlrgateway_ddotServers}
    IsSecure: ${mlrgateway_ddotServers_IsSecure}

legacyTransformer:
  ribbon:
    listOfServers: ${mlrgateway_legacyTransformerServers}
    IsSecure: ${mlrgateway_legacyTransformerServers_IsSecure}

legacyValidator:
  ribbon:
    listOfServers: ${mlrgateway_legacyValidatorServers}
    IsSecure: ${mlrgateway_legacyValidatorServers_IsSecure}

legacyCru:
  ribbon:
    listOfServers: ${mlrgateway_legacyCruServers}
    IsSecure: ${mlrgateway_legacyCruServers_IsSecure}

fileExport:
  ribbon:
    listOfServers: ${mlrgateway_fileExportServers}
    IsSecure: ${mlrgateway_fileExportServers_IsSecure}

notification:
  ribbon:
    listOfServers: ${mlrgateway_notificationServers}
    IsSecure: ${mlrgateway_notificationServers_IsSecure}

eureka:
  client:
    enabled: false

feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: ${mlrgateway_ribbonMaxAutoRetries}
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: ${mlrgateway_ribbonConnectTimeout}
  ReadTimeout: ${mlrgateway_ribbonReadTimeout}
  OkToRetryOnAllOperations: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: ${mlrgateway_hystrixThreadTimeout}

logging:
  level:
    org:
      springframework: ${mlrgateway_springFrameworkLogLevel}

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ${oauthClientId}
      clientSecret: ${oauthClientSecret}
      accessTokenUri: ${oauthClientAccessTokenUri}
      userAuthorizationUri: ${oauthClientAuthorizationUri}
    resource:
      id: ${oauthResourceId}
      jwt:
        keyUri: ${oauthResourceTokenKeyUri}