server:
  port: ${serverPort:8443}
  use-forward-headers: true
  session:
    timeout: ${sessionTimeout:43200}
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
    enabled-protocols: TLSv1.2

security:
  require-ssl: true
  basic:
    enabled: false
  maintenanceRoles: ${maintenanceRoles:}
  token:
    claims:
      email: email
      username: preferred_username

spring:
  http:
    multipart:
      enabled: true
  security:
    oauth2:
      client:
        registration: 
          wma-keycloak: 
            client-id: ${oauthClientId:}
            client-secret: ${oauthClientSecret:}
        provider:
          wma-keycloak:
            issuer-uri: ${oauthIssuerUri:}

logging:
  level:
    org:
      springframework: ${mlrgateway_springFrameworkLogLevel:INFO}

notification:
  email:
    cc-list: ${emailCCList:}

springdoc:
  swagger-ui:
    path: /swagger-ui/api-docs.html

eureka:
  client:
    enabled: false

feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: ${mlrgateway_ribbonMaxAutoRetries}
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: ${mlrgateway_ribbonConnectTimeout}
  ReadTimeout: ${mlrgateway_ribbonReadTimeout}
  OkToRetryOnAllOperations: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: ${mlrgateway_hystrixThreadTimeout}

zuul:
  retryable: true
  ribbonIsolationStrategy: SEMAPHORE
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredHeaders: Access-Control-Allow-Credentials,Access-Control-Allow-Origin
  routes:
    legacyCruBase:
      path: /monitoringLocations**
      serviceId: mlrLegacyCru
      stripPrefix: false
    legacyCruPlus:
      path: /monitoringLocations/**
      serviceId: mlrLegacyCru
      stripPrefix: false

mlrDdot:
  ribbon:
    listOfServers: ${mlrgateway_ddotServers}
    IsSecure: ${mlrgateway_ddotIsSecure:true}

mlrLegacyTransformer:
  ribbon:
    listOfServers: ${mlrgateway_legacyTransformerServers}
    IsSecure: ${mlrgateway_legacyTransformerIsSecure:true}

mlrLegacyValidator:
  ribbon:
    listOfServers: ${mlrgateway_legacyValidatorServers}
    IsSecure: ${mlrgateway_legacyValidatorIsSecure:true}

mlrLegacyCru:
  ribbon:
    listOfServers: ${mlrgateway_legacyCruServers}
    IsSecure: ${mlrgateway_legacyCruIsSecure:true}

mlrFileExport:
  ribbon:
    listOfServers: ${mlrgateway_fileExportServers}
    IsSecure: ${mlrgateway_fileExportIsSecure:true}

mlrNotification:
  ribbon:
    listOfServers: ${mlrgateway_notificationServers}
    IsSecure: ${mlrgateway_notificationIsSecure:true}
